name: "Get currently deployed task definition"
description: "Gets the ECS task definition that is currently running on the ECS service"

inputs:
  name:
    description: "The name of the ECS task definition"
    required: true

outputs:
  image:
    description: The docker image
    value: ${{ steps.task-definition.outputs.image }}

runs:
  using: "composite"
  steps:
    - name: Get current task definition image
      id: task-definition
      shell: bash
      run: |
        IMAGE=$(aws ecs describe-task-definition --task-definition ${{ inputs.name }} | jq -r '.taskDefinition.containerDefinitions[0].image')
        echo "::set-output name=image::$IMAGE"
