name: "Run terraform plan and create PR comment"
description: "Runs terraform plan and adds a comment to the PR if it contains changes. Make sure to set terraform_wrapper: false on hashicorp/setup-terraform"

inputs:
  cmd:
    description: "The terraform plan command. '-detailed-exitcode' will be added by this action"
    required: false
    default: terraform plan
  label:
    description: "A string that is added to the PR comment to distinguish it from other comments of this action"
    required: false
  working-directory:
    description: "The directory to run the terraform plan command in"
    required: false
    default: .
  github-token:
    description: "The GitHub token to use for authentication for creating the PR comment"
    required: true

runs:
  using: "composite"

  steps:
    - name: Run terraform plan
      id: plan
      shell: bash -o pipefail {0} # disable fail fast, we will react on the exit code manually in the steps afterwards
      # https://trstringer.com/github-actions-multiline-strings/
      run: |
        ${{ inputs.cmd }} -detailed-exitcode -no-color 2>&1 | tee /tmp/terraform-plan.log
        echo "::set-output name=exitcode::$?"

        echo "TF_OUTPUT<<TF_OUTPUT_EOF" >> $GITHUB_ENV
        cat /tmp/terraform-plan.log >> $GITHUB_ENV
        echo "TF_OUTPUT_EOF" >> $GITHUB_ENV
      working-directory: ${{ inputs.working-directory }}

    - name: Add PR comment if plan has changes
      if: steps.plan.outputs.exitcode == '2'
      uses: d-i-p/terraform-actions/plan-pr-comment@main
      with:
        github-token: ${{ inputs.github-token }}
        plan-stdout: ${{ env.TF_OUTPUT }}
        environment: ${{ inputs.environment }}

    - name: Exit if terraform plan failed
      if: steps.plan.outputs.exitcode == '1'
      shell: bash
      run: exit 1