name: "Run terraform plan and create PR comment"
description: "Runs terraform plan and adds a comment to the PR if it contains changes"

inputs:
  cmd:
    description: "The terraform plan command. '-detailed-exitcode' and '-no-color' will be added by this action"
    required: false
    default: terraform plan
  label:
    description: "A string that is added to the PR comment to distinguish it from other comments of this action"
    required: false
  working-directory:
    description: "The directory to run the terraform plan command in"
    required: false
    default: .
  github-token:
    description: "The GitHub token to use for authentication for creating the PR comment"
    required: true

runs:
  using: "composite"

  steps:
    - name: Run terraform plan
      id: plan
      shell: bash
      run: ${{ inputs.cmd }} -detailed-exitcode -no-color || true
      working-directory: ${{ inputs.working-directory }}

    - name: Add PR comment if plan has changes
      if: steps.plan.outputs.exitcode == '2'
      uses: d-i-p/terraform-actions/plan-pr-comment@main
      with:
        github-token: ${{ inputs.github-token }}
        plan-stdout: ${{ steps.plan.outputs.stdout }}
        label: ${{ inputs.label }}

    - name: Exit if terraform plan failed
      if: steps.plan.outputs.exitcode == '1'
      shell: bash
      run: exit 1
