name: "Run terraform plan and create PR comment"
description: "Runs terraform plan and adds a comment to the PR if it contains changes"

inputs:
  cmd:
    description: "The terraform plan command. '-no-color' and '-detailed-exitcode' will be added by this action"
    required: false
    default: terraform plan
  environment:
    description: "The name of the environment to add to the description"
    required: false
  working-directory:
    description: "The directory to run the terraform plan command in"
    required: false
    default: .
  github-token:
    description: "The GitHub token to use for authentication for creating the PR comment"
    required: true

runs:
  using: "composite"

  steps:
    - name: Run terraform plan
      id: plan
      shell: bash
      # workaround for continue-on-failure: true not available in composite actions
      run: ${{ inputs.cmd }} -no-color -detailed-exitcode || PLAN_CODE=$?
      working-directory: ${{ inputs.working-directory }}

    - name: debug
      shell: bash
      run: echo "plan code is $PLAN_CODE"

    - name: Add PR comment if plan has changes
      if: steps.plan.outputs.actual-exit-code == '2'
      uses: ./plan-pr-comment
      with:
        github-token: ${{ inputs.github-token }}
        plan-stdout: ${{ steps.plan.outputs.stdout }}
        environment: ${{ inputs.environment }}

    - name: Exit if terraform plan failed
      if: steps.plan.outputs.actual-exit-code == '1'
      shell: bash
      run: exit 1
